export const componentMetadata = {
  Button: { source: 'Buttons', anatomy: ['container', 'optional leading icon', 'label', 'optional trailing icon'], variants: ['primary', 'secondary', 'tertiary', 'ghost', 'destructive'], sizes: ['sm · 34px', 'md · 40px'], rule: 'Use filled teal once per action region.' },
  IconButton: { source: 'Icon buttons', variants: ['shell · 40px circle', 'row · 34px rounded', 'destructive · 34px rounded'], rule: 'Always provide an accessible label and native tooltip.' },
  StatusBadge: { source: 'Badges & status taxonomy', height: '26px', anatomy: ['6px dot', 'label'], rule: 'Tone communicates domain state, not decoration.' },
  ReadinessChip: { source: 'Chips & avatars', labels: ['Clear', 'Due soon', 'Action needed'], rule: 'Clickable and restricted to the three readiness meanings.' },
  Avatar: { source: 'Chips & avatars', content: 'Stable initials and person-specific tint', sizes: ['28px', '34px', '40px'] },
  Fields: { source: 'Form controls', height: '40px', radius: '10px', exception: 'Global search is 44px with a 12px radius.' },
  Checkbox: { source: 'Form controls', size: '20px', states: ['unchecked', 'checked', 'indeterminate', 'disabled'] },
  SegmentedControl: { source: 'Form controls', height: '38px', rule: 'Use for a short, mutually exclusive view choice.' },
  Tabs: { source: 'Navigation', height: '44px', rule: 'Tab counts mean items requiring action, never totals.' },
  Pagination: { source: 'Navigation', size: '32px', rule: 'Active page uses the pink accent.' },
  Toolbar: { source: 'Toolbar', order: ['search', 'filters', 'secondary action', 'primary action'] },
  DataTable: { source: 'Data table', rowHeight: '56px minimum', radius: '16px', rule: 'Default to six columns. Fold secondary values below primary values.' },
  SummaryPanel: { source: 'Summary panel', radius: '16px', rule: 'Title sits inside a tinted strip; metric cells fill the grid.' },
  EmptyState: { source: 'Empty & loading states', rule: 'Name the empty result, explain recovery and offer at most one action.' },
  Modal: { source: 'Overlays', radius: '20px', rule: 'Centred with a floating shadow and explicit close action.' },
  Menu: { source: 'Overlays', radius: '16px', rule: 'Anchor to its trigger and keep the selected item visible.' },
  PriceCell: { source: 'Rate-card extension', states: ['entered', 'included', 'complimentary', 'on-request', 'not-offered', 'missing'], rule: 'Blank means missing, never free.' },
  RateCardTable: { source: 'Operational table extension', rule: 'One visible row per product or priced combination; never hide fee identity in a row expander.' },
} as const
